Analytics component
yext-pages/sites-basic-starter pull request #1
Opened 2022-02-18 15:54 UTC by JessicaTXu

2022-02-18 19:30 UTC, bmayyext commented on src/Analytics.js
> +    jsonData['businessids'] = businessId;
is the key supposed to be 'businessids' or 'businessId'?

2022-02-18 19:32 UTC, bmayyext commented on partials/analytics.hbs
> +        jsonData['siteId'] = siteId;
var jsonData = {
  'pagesReferrer': window.document.referrer,
  'pageurl': window.location.pathname,
  'eventType': eventType,
  'businessids': businessId,
  'siteId': siteId,
};

2022-02-18 19:33 UTC, bmayyext commented on partials/analytics.hbs
> +        jsonData['businessids'] = businessId;
is the key supposed to be 'businessids' or 'businessId'?

2022-02-18 19:33 UTC, bmayyext commented on partials/analytics.hbs
> +    let p = '//www.yext-pixel.com/store_pagespixel?product=sites';
`const`, not `let`

2022-02-18 19:35 UTC, bmayyext commented on templates/entity-page.hbs
> +                "ce_summerOutfit"
this doesn't seem like it should have changed

2022-02-18 19:35 UTC, bmayyext commented on partials/analytics.hbs
> +    return p;
indent right 2 spaces

2022-02-18 19:38 UTC, bmayyext commented on sites-global/global.json
> +    "accountId": "1234",
was this change supposed to be made?

2022-02-18 19:38 UTC, bmayyext commented on sites-global/global.json
> +    "siteId": "1234"
based on other values, should this be empty as well?

2022-02-18 19:39 UTC, bmayyext requested changes
Indent size is generally inconsistent (2 spaces on some lines, 4 spaces on others).

2022-02-18 19:52 UTC, JessicaTXu commented on src/Analytics.js
> +    jsonData['businessids'] = businessId;
businessids is what's expected

2022-02-18 21:49 UTC, JessicaTXu commented on sites-global/global.json
> +    "accountId": "1234",
Yeah, this is just something I'm using in lieu of https://yexttest.atlassian.net/browse/SPR-4278. Will undo this change once the massaged data is available.

2022-02-23 14:54 UTC, JessicaTXu commented
Looks like analytics.js is not longer the strictmode, it now includes the pixel stuff, but I'm still getting Uncaught ReferenceError: trackAnalytics is not defined

2022-02-23 15:53 UTC, bmayyext commented on src/Analytics.js
> +      'siteId': siteId,
minor, but use 2 space indents

2022-02-23 15:56 UTC, bmayyext commented on src/Analytics.js
> +    if (data.hasOwnProperty(key)) {
should we also check that the data value is not empty, i.e.

`if (data.hasOwnProperty(key) && !!data[key]) {`

2022-02-23 22:48 UTC, bmayyext reviewed
We should probably squash this into one commit before merging, right?

2022-02-24 19:09 UTC, mkilpatrick commented
LGTM

2022-02-24 19:39 UTC, bmayyext approved these changes

2022-02-24 23:14 UTC, merged